### ISSUE TITLE
Convert Writing The Pitch For Your WordPress Talk Lesson Plan

### ISSUE THREAD

**Issue by JulieKuehl** [wptrainingteam/writing-the-pitch-for-your-wordpress-talk#1]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [x]  clean up the Markdown
- [x]  download the old images
- [x]  upload the images into GitHub
- [x]  swap out the image links

**Comment by JulieKuehl** [comment]
https://make.wordpress.org/training/handbook/speaker-training/writing-the-pitch-for-your-wordpress-talk/

**Comment by pbrocks** [comment]
Looks like the Make site was crawled once in September 2015. So if the missing images were on the site at that point, we may find them there: https://web.archive.org/web/20150906192233/https://make.wordpress.org/training/handbook/
